config/routes.rb
Rails.application.routes.draw do
  
  get "set_page_size" => "home#set_page_size"
  get "set_page_size/:size" => "home#set_page_size"
  
  resources :favorites, only: [:create, :destroy] do
    collection do
      get "add_primes"
    end
  end
  
  root 'home#display'
  
  get "/:page" => 'home#display', as: :page
  
  namespace :api do
    namespace :v1 do
       get 'numbers/:page/:page_size' => "numbers#display"
       resources  :favorites, only: [:create, :destroy, :index]
    end
  end

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  validates :number, uniqueness: true
  validates :number, inclusion: 1..10**12  # 1 .. 100,000,000,000
  def fizzbuzz
    FizzBuzzService.new.fizzbuzz(number)
  end
  def as_json(options={}) 
    {
      number: number,
      fizzbuzz: fizzbuzz,
      id: id
    }
  end
end

app/controllers/api/v1.rb
module Api::V1
  
end

app/controllers/api/v1/api_controller.rb
module Api::V1
  class ApiController < ApplicationController
      
  end
end

app/controllers/api/v1/favorites_controller.rb
module Api::V1
  class FavoritesController < ApiController
    skip_before_action :verify_authenticity_token, only: [:create, :destroy] #As there is no user verification I'm not creating one for this place
    
    def create
      Favorite.create favorite_params
      show_all
    end
    
    def destroy
      Favorite.find(params[:id]).destroy
      show_all
    end
    
    def index
      show_all
    end
    
    private
    def show_all
      @favorites=Favorite.all.order :number
      render json: @favorites
    end
    
    def favorite_params
      params.require(:favorite).permit :number
    end

  end
end

app/controllers/api/v1/numbers_controller.rb
module Api::V1
  class NumbersController < ApiController
      def display
        @page = params[:page].to_i
        @page_size = params[:page_size].to_i 
        fizzbuzz = FizzBuzzService.new @page, @page_size
        @last_page = fizzbuzz.get_last_page
        
        @numbers = fizzbuzz.serve
        render json: @numbers
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    Favorite.create favorite_params
    redirect_to page_path(params[:page])
  end

  def destroy
    Favorite.find(params[:id]).destroy
    redirect_to page_path(params[:page])
  end
  
  def add_primes
    FavoriteFromComplexOperationJob.perform_later params[:prime].to_i
    redirect_to page_path(params[:page]), flash: {notice: "Your process has started and will be finished soon"}
  end
  
  private
  def favorite_params
    params.require(:favorite).permit :number
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def display
    @page = params[:page].to_i
    @page_size = session[:page_size]
    @page_size ||= 100
    fizzbuzz = FizzBuzzService.new @page, @page_size
    @last_page = fizzbuzz.get_last_page
    @numbers = fizzbuzz.serve
    @favorites = Favorite.all.order(:number)
  end

  def set_page_size
    fizzbuzz = FizzBuzzService.new params[:current_page], session[:page_size] #Original Page Size
    session[:page_size] = params[:page_size]
    page = fizzbuzz.change_page_size session[:page_size], params[:current_page] #Returns new Page Number
    redirect_to page_path(page)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def page page_num, text, valid = true, ending_dots = true
    active=(valid)? "" : "disabled"
    url=(valid)? page_path(page_num) : "#"
    link=link_to text, url
    content_tag :li, link, class: active
  end
  
  def current_page page_num
    link=link_to page_num, page_path(page_num)
    content_tag :li, link, class: "active"
  end
  
  def add_favorite number
    link_to "(Add)", favorites_path(favorite:{number: number}, page: @page), method: :post, class: "btn-sm btn-success"
  end
  
  def remove_favorite number
    link_to "(Remove)", favorite_path(Favorite.find_by(number: number), page: @page), method: :delete, class: "btn-sm btn-danger"
  end
end

app/views/home/_favorite.html.erb
<div class="col-xs-6 col-md-3">
	<div class="thumbnail">
	  <span class="glyphicon glyphicon-star"></span><span>(<%= favorite.number %>)</span>
	  <span class="badge"><%= favorite.fizzbuzz %></span>
	  <hr>
	  <center><%= remove_favorite favorite.number %></center>
	</div>
</div>

app/views/home/_number.html.erb
<div class="col-xs-4 col-md-2">
	<div class="thumbnail">
  	<span class="glyphicon glyphicon-star<%if !number[:favorite]%>-empty<%end%>"></span>
  	<span><%=number[:fizzbuzz]%></span>
  	<hr>
  	<center>
  		<% if number[:favorite] %>
  			<%= remove_favorite number[:value] %>
  		<% else %>
  			<%= add_favorite number[:value] %>
  		<% end %>
  	</center>
	</div>
</div>

app/views/home/_paginators.html.erb
<nav>
  <ul class="pagination">
    <%= page 0, "<<" %>
  	<%= page @page - 1, "<", @page > 0 %>
  	<%= current_page @page%>
  	<%= page @page + 1, ">", @page < @last_page %>
  	<%= page @last_page, ">>", true %>
  </ul>
</nav>

app/views/home/display.html.erb
<h1>FizzBuzz Test</h1>
<h3>Your Favorite Numbers</h3>
<table>
  	<%= @favorites.each_slice 4 do |row| %>
  			<div class="row">
  			 <%= render partial: "favorite", collection: row %>
  			</div>
  	<%end%>
</table>
<hr>
Add From primes up to:
<%= form_tag add_primes_favorites_path, method: :get do |f| %>
<%= hidden_field_tag "page", @page %>
<%= number_field_tag :prime, 1%>
<%= submit_tag "Add" %>
<% end %>
<hr>
<hr>
<h3>Page <%= @page.to_i %> all numbers:</h3>
Page Size: 
<%= form_tag set_page_size_path, method: :get do |f| %>
<%= hidden_field_tag "current_page", @page, id: "current_page" %>
<%= number_field_tag "page_size", @page_size %>
<%= submit_tag "Change Size" %>
<%end%>
<table>
	<%= @numbers.each_slice 6 do |row| %>
		<div class="row">
		<%= render partial: "number", collection: row %>
		</div>
	<%end%>
</table>
<hr>
<%= render partial: "paginators" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FizzBuzz</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <b><%=flash[:notice]%></b>
	<div class="container-fluid">
		<%= yield %>
	</div>
</body>
</html>